# Generated by Django 4.2.3 on 2023-08-19 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itdesk',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='itdesk',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterModelTable(
            name='itdesk',
            table='ITDESK',
        ),
    ]
