# Generated by Django 4.2.3 on 2023-08-26 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samapp', '0002_alter_itdesk_id_alter_itdesk_name_alter_itdesk_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itdesk',
            old_name='name',
            new_name='username',
        ),
    ]
