# Generated by Django 4.2.3 on 2023-09-18 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samapp', '0003_rename_name_itdesk_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='up_load',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'up_load',
            },
        ),
    ]
